server:
  port: 8000
spring:
  #数据源
  datasource:
    #当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql的驱动程序类
    # 使用旧版本驱动(com.mysql.jdbc.Driver)，会有下边的报错
    #Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'.....
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接地址
#    url: jdbc:mysql://127.0.0.1:3306/foolox_game?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/tim_game?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      #配置druid过滤器,开启监控(统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙)
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  #缓存
  hazelcast:
    config: classpath:config/hazelcast.xml

mybatis:
  #定义所有操作类的别名所在包
  type-aliases-package: com.foolox.repo.domain
  #mybatis主配置
  configuration:
    map-underscore-to-camel-case: true #下划线映射为驼峰命名
    default-fetch-size: 100
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #所有的mapper映射文件
  mapper-locations: classpath:mybatis/mapper/*.xml

##  activemq配置
#  activemq:
#    broker-url: http://192.168.159.186:5672
#    user: guest
#    password: guest
#
#
##mybatis
#mybatis:


#logging:
#  config:
##logging:
##  level: debug cn.mylava.seckill.dao
#
#
#
#

foolox.server.port:  7890

